import test from "node:test";
import assert from "node:assert/strict";
import { createServer } from "node:http";
import { mkdtemp, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve, dirname, basename } from "node:path";
import { createApi } from "../server/api.js";

test("real HTTP server: registration, session, protected file, logout and persistence", async () => {
  const directory = await mkdtemp(resolve(tmpdir(), "viana-server-test-"));
  const api = createApi({ dataDir: directory, secureCookies: false });
  const server = createServer(api.handler);
  await new Promise((done) => server.listen(0, "127.0.0.1", done));
  const origin = `http://127.0.0.1:${server.address().port}`;
  let cookie = "";
  const request = (path, data, overrides = {}) => fetch(origin + path, {
    method: data ? "POST" : "GET", headers: { Origin: origin, "Content-Type": "application/json", Cookie: cookie, ...overrides }, body: data ? JSON.stringify(data) : undefined,
  });
  try {
    assert.equal((await request("/api/health")).status, 200);
    assert.equal((await request("/api/designs/test-wall/download")).status, 401);
    let invalidLogin = await request("/api/auth/login", { identifier: "Viana", password: "A-test-password123" });
    assert.equal(invalidLogin.status, 400);
    assert.match((await invalidLogin.json()).error, /registered email address or phone/);
    invalidLogin = await request("/api/auth/login", { identifier: "owner@example.com", password: "A-test-password123" });
    assert.equal(invalidLogin.status, 409);
    assert.match((await invalidLogin.json()).error, /No accounts/);
    const registration = { name: "Test Customer", email: "test@example.com", phone: "9000000001", password: "A-test-password123", confirmPassword: "A-test-password123", role: "admin" };
    assert.equal((await request("/api/auth/register", registration, { Origin: "https://attacker.example" })).status, 403);
    let response = await request("/api/auth/register", registration);
    assert.equal(response.status, 200);
    const setCookie = response.headers.get("set-cookie");
    assert.match(setCookie, /HttpOnly/); assert.match(setCookie, /SameSite=Strict/);
    cookie = setCookie.split(";")[0];
    const { user } = await response.json();
    assert.equal(user.role, "user"); assert.equal(user.password, undefined);
    assert.equal((await (await request("/api/auth/session")).json()).user.id, user.id);
    assert.equal((await request("/api/designs/test-wall/download")).status, 403);
    assert.equal((await request("/api/auth/register", registration)).status, 409);
    const bytes = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
    await writeFile(resolve(api.filesRoot, "test.png"), bytes);
    api.db.prepare("INSERT INTO designs VALUES (?,?)").run("test-wall", "test.png");
    api.db.prepare("INSERT INTO entitlements VALUES (?,?)").run(user.id, "test-wall");
    response = await request("/api/designs/test-wall/download");
    assert.equal(response.status, 200);
    assert.equal(response.headers.get("content-type"), "image/png");
    assert.equal(response.headers.get("cache-control"), "private, no-store");
    assert.match(response.headers.get("content-disposition"), /^attachment/);
    assert.deepEqual(Buffer.from(await response.arrayBuffer()), bytes);
    api.db.prepare("UPDATE designs SET file=? WHERE id=?").run("../studio.sqlite", "test-wall");
    assert.equal((await request("/api/designs/test-wall/download")).status, 403);
    api.db.prepare("UPDATE designs SET file=? WHERE id=?").run("test.png", "test-wall");
    api.db.prepare("DELETE FROM entitlements WHERE user_id=?").run(user.id);
    assert.equal((await request("/api/designs/test-wall/download")).status, 403);
    const expiredCookie = cookie;
    assert.equal((await request("/api/auth/logout", {})).status, 200);
    assert.equal((await request("/api/designs/test-wall/download", null, { Cookie: expiredCookie })).status, 401);
    response = await request("/api/auth/login", { identifier: registration.email, password: registration.password });
    assert.equal(response.status, 200);
    assert.notEqual(response.headers.get("set-cookie").split(";")[0], expiredCookie);
    assert.equal((await request("/api/auth/login", { identifier: registration.email, password: "wrong-password" })).status, 401);
    assert.equal((await request("/api/auth/admin-login", { identifier: registration.email, password: registration.password })).status, 403);
    const owner = await api.createUser({ name: "Test Owner", email: "owner@example.com", phone: "9000000002", password: "Owner-password123" }, "admin");
    await request("/api/auth/logout", {});
    cookie = "";
    response = await request("/api/auth/login", { identifier: owner.email, password: "Owner-password123" });
    assert.equal(response.status, 200);
    assert.equal((await response.json()).user.role, "admin");
    cookie = response.headers.get("set-cookie").split(";")[0];
    assert.equal((await (await request("/api/auth/session")).json()).user.role, "admin");
    await request("/api/auth/logout", {});
    cookie = "";
    response = await request("/api/auth/admin-login", { identifier: owner.email, password: "Owner-password123" });
    assert.equal(response.status, 200);
    assert.equal((await response.json()).user.role, "admin");
    assert.match(response.headers.get("set-cookie"), /HttpOnly/);
    const ownerCookie = response.headers.get("set-cookie").split(";")[0];
    await assert.rejects(api.resetAdminPassword(registration.email, "New-owner-password123"), /No admin account/);
    await assert.rejects(api.resetAdminPassword(owner.email, "short"), /10–128/);
    await api.resetAdminPassword(owner.email, "New-owner-password123");
    assert.equal((await (await request("/api/auth/session", null, { Cookie: ownerCookie })).json()).user, null);
    assert.equal((await request("/api/auth/login", { identifier: owner.email, password: "Owner-password123" })).status, 401);
    assert.equal((await request("/api/auth/login", { identifier: owner.email, password: "New-owner-password123" })).status, 200);
    assert.equal((await request("/api/auth/admin-login", { identifier: owner.email, password: "New-owner-password123" })).status, 200);
    response = await request("/api/auth/login", { identifier: registration.email, password: registration.password, admin: true, role: "admin" });
    assert.equal(response.status, 200);
    assert.equal((await response.json()).user.role, "user");
    const stored = api.db.prepare("SELECT * FROM users WHERE id=?").get(user.id);
    assert.notEqual(stored.password, registration.password);
    assert.ok(stored.salt);
    const second = createApi({ dataDir: directory, secureCookies: false });
    assert.equal(second.db.prepare("SELECT id FROM users WHERE email=?").get(registration.email).id, user.id);
    second.close();
    for (let i = 0; i < 10; i++) response = await request("/api/auth/login", { identifier: registration.email, password: "wrong-password" });
    assert.equal(response.status, 429);
    assert.equal(response.headers.get("retry-after"), "900");
  } finally {
    await new Promise((done) => server.close(done));
    api.close();
    assert.equal(dirname(directory), resolve(tmpdir()));
    assert.ok(basename(directory).startsWith("viana-server-test-"));
    await rm(directory, { recursive: true, force: true });
  }
});
